# Generated by Django 3.2.9 on 2021-11-21 20:44

from django.db import migrations, models
import django.db.models.deletion
import touristApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=touristApp.models.get_image_path)),
                ('price', models.IntegerField()),
                ('cardDescription', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('personNum', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHot',
            fields=[
                ('country', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=touristApp.models.get_image_path)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('personNum', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelMed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=touristApp.models.get_image_path)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelCountryDescription',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='touristApp.travelcountry')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelCountryInclude',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='touristApp.travelcountry')),
            ],
        ),
        migrations.CreateModel(
            name='TravelCountryProgram',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='touristApp.travelcountry')),
            ],
        ),
    ]
